### ISSUE TITLE
'syntax error: invalid arithmetic operator' 

### ISSUE THREAD

**Issue by junghan0611** [padsys/PMIdioBench#1]
I'm working on Fedora 33 and bash 5.0.17(1)). 

I don't know why bash scripts give arithmetic syntax error. 
You implemented scripts with 'bc', it's correct I think. 

Did you see that errors below? 

Thanks...

--------
**$cd Bench;./scripts/run_all.sh**
...

scripts/test_i2.sh 
DRAM load and nt-store b/w
--------------): [w(20)][100.0%][w=47.3GiB/s][w=12.4M IOPS][eta 00m:00s]k IOPS][eta 00m:00s]
SeqR
--------------

	64	128	256	512	1024	2048	4096	
20	**scripts/get_fio_results.sh: line 32: ((: 1880.71
0 : syntax error: invalid arithmetic operator** (error token is ".71
0 ")
1880.71
1880.91	scripts/get_fio_results.sh: line 32: ((: 3740.05
0 : syntax error: invalid arithmetic operator (error token is ".05
0 ")
3740.05
3740.45	scripts/get_fio_results.sh: line 32: ((: 7328.31
0 : syntax error: invalid arithmetic operator (error token is ".31
0 ")
7328.31
7329.08	scripts/get_fio_results.sh: line 32: ((: 13514.70
0 : syntax error: invalid arithmetic operator (error token is ".70
0 ")
13514.70
13516.45	scripts/get_fio_results.sh: line 32: ((: 19781.87
0 : syntax error: invalid arithmetic operator (error token is ".87
0 ")
19781.87
19785.35	scripts/get_fio_results.sh: line 32: ((: 25314.71
0 : syntax error: invalid arithmetic operator (error token is ".71
0 ")
25314.71
25319.60	scripts/get_fio_results.sh: line 32: ((: 31630.67
0 : syntax error: invalid arithmetic operator (error token is ".67
0 ")
31630.67
31638.36

**Comment by shashankgugnani** [comment]
Can you paste the contents of one of the output log files? You can find it in the results folder created under the Bench folder. This will us help understand the reason for the error.

**Comment by shashankgugnani** [comment]
Fixed by c7b3950eda85b51a106159d9192c984e54b1c05b.
